### PR TITLE
CI fixes for conda forge

### LINKED ISSUE #28: Add tests and CI
We should add tests and CI to check that things aren't breaking.

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #28

### CODE REVIEW

**Comment by hmacdope** [comment]
@mikemhenry @kaminow I think the failure to solve for 3.9 and 3.11 is due to BLAS restrictions in our conda recipie for `DGL`, pushing a hopeful fix now https://github.com/conda-forge/dgl-feedstock/pull/20

**Comment by hmacdope** [comment]
@mikemhenry would you mind having a look here at the conflict graph, as far as I can tell there are 3.9 has a bunch of issues and 3.11 is blocked by some pytorch-cluster issues.

**Comment by hmacdope** [comment]
If we can't get to the bottom of this, then we may have to use the `dglteam` channel in the short term.

**Comment by ijpulidos** [comment]
Interestingly enough, I can create an environment fine with `mamba` (not `micromamba`) if I use the following env file (removed the `dglteam` channel and added `python=3.9`).

```yaml
name: test
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - numpy
  - h5py
  - e3nn
  - dgllife
  - dgl
  - rdkit
  # testing dependencies
  - pytest
  - pytest-cov
  - codecov

```

and running `mamba env create -f devtools/conda-envs/test_env.yaml -n mtenn-test`

**Comment by mikemhenry** [comment]
> If we can't get to the bottom of this, then we may have to use the dglteam channel in the short term. @kaminow

Looking into this, but IMHO, way better to just drop python 3.9 support (or not test it on CI since it sounds like it is only a problem on CI, since @ijpulidos can make an env and so can I, `micromamba create -n mtenn-py39 --dry-run --file devtools/conda-envs/test_env.yaml python=3.9` works for me on on Linux)

**Comment by mikemhenry** [comment]
`CONDA_OVERRIDE_CUDA="" micromamba create -n mtenn-py39 --dry-run --file devtools/conda-envs/test_env.yaml python=3.9` works for me as well, thought I should check that to make sure it wasn't a GPU thing

**Comment by mikemhenry** [comment]
So my vote is to not worry about this unless we need python 3.9 in a production environment.

**Comment by kaminow** [comment]
I think the main worry with ignoring the issues with 3.9 is that it may mess with the `asapdiscovery` CI for 3.9, so we'd have to drop it there as well

**Comment by mikemhenry** [comment]
It looks like we have `mtenn` in our CI already there and it is working https://github.com/choderalab/asapdiscovery/blob/main/devtools/conda-envs/asapdiscovery-ubuntu-latest.yml#L90 so we wouldn't have to drop 3.9 from our CI matrix for `asapdiscovery`

**Review by kaminow — APPROVED** [review]
going to approve this based on our discussion today

**Pull request merged**
