### PR TITLE
Build out docs

### PR DESCRIPTION
**Pull request by kaminow**
Fully build out the docs, including more in-depth explanations of the different components and some how-to guides.

API Docs:

- [x] `combination`
- [x] `config`
- [x] `__init__`
- [x] `model`
- [x] `readout`
- [x] `representation`
- [x] `strategy`
- [x] `conversion_utils/e3nn`
- [x] `conversion_utils/gat`
- [x] `conversion_utils/__init__`
- [x] `conversion_utils/schnet`
- [x] `conversion_utils/visnet`

### CODE REVIEW

**Comment by ijpulidos** [comment]
Docs are looking goooood! :)

**Comment by mikemhenry** [comment]
I think the install documentation needs to be updated. I don't think this file exists `mtenn/devtools/conda-envs/mtenn.yaml`. I would update with how to install on conda-forge, then I would explain how to install the development version. 

Once you do that give me a ping on slack and I will give it a review :)

**Comment by kaminow** [comment]
@hmacdope and/or @mikemhenry I think these are done and ready for a review!

**Review by hmacdope — APPROVED** [review]
LGTM!

**Pull request merged**
