### PR TITLE
Fix gitignore version

### LINKED ISSUE #16: Add `_version.py` to gitignore
Having `_version.py` tracked  made it hacky to do a release as had to preset it and then commit and push tags. 

For the next release we should remove it from tracking.

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #16

### CODE REVIEW

**Comment by hmacdope** [comment]
@mikemhenry could I snag a review here :)

**Comment by mikemhenry** [comment]
This should work, I will give it a test later today

**Comment by hmacdope** [comment]
I found i had to do a `pip install -e .` install rather than `pip install .` build so that git-describe could find the right spot. Have you had this issue at any point?

**Comment by mikemhenry** [comment]
Hmm, try adding a tag (don't push it) and see if with a `pip install .` the version you expect is reported? I will look into this as well

**Comment by hmacdope** [comment]
Yeah it seems to complain that git describe isn't working if not a `pip install -e .`

**Comment by hmacdope** [comment]
Shouldn't do this.

**Pull request closed without merging**
